package fr.unreal852.sunrealcore.specials.events.inventory;

public interface IInventoryClickable extends IInventoryLeftClickable, IInventoryRightClickable, IInventoryMiddleClickable, IInventoryShiftLeftClickable, IInventoryShiftRightClickable, IInventoryWindowBorderLeftClickable, IInventoryWindowBorderRightClickable
{
}
